name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: webappregistry1.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t webappregistry1.azurecr.io/my-web-app:v4 .
        docker push webappregistry1.azurecr.io/my-web-app:v4

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Azure Web App Deployment
      uses: azure/webapps-deploy@v2
      with:
        app-name: myapp121
        slot-name: production
        images: webappregistry1.azurecr.io/my-web-app:v4
